const calculate = require('../lib/index')

describe('pop calculator', () => {
    it('calculates with valid givens', () => {
        const portData = {
            crew: [
                {
                    morale: 4010,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 3780,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 4230,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 4200,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 3780,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 3150,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    morale: 40,
                    seafaring: 4210,
                    combat: 30,
                    crewType: 'stargazer',
                },
                {
                    morale: 10,
                    seafaring: 3990,
                    combat: 0,
                    crewType: 'stargazer',
                },
                {
                    morale: 0,
                    seafaring: 3570,
                    combat: 0,
                    crewType: 'stargazer',
                },
                {
                    morale: 0,
                    seafaring: 3410,
                    combat: 0,
                    crewType: 'stargazer',
                },
                {
                    morale: 10,
                    seafaring: 3360,
                    combat: 0,
                    crewType: 'stargazer',
                },
                {
                    morale: 0,
                    seafaring: 3990,
                    combat: 0,
                    crewType: 'stargazer',
                },
                {
                    morale: 20,
                    seafaring: 0,
                    combat: 4020,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 0,
                    seafaring: 0,
                    combat: 4200,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 0,
                    seafaring: 0,
                    combat: 3580,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 0,
                    seafaring: 100,
                    combat: 3360,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 10,
                    seafaring: 0,
                    combat: 4200,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 0,
                    seafaring: 0,
                    combat: 3410,
                    crewType: 'gu-bodyguard',
                },
                {
                    morale: 1300,
                    seafaring: 0,
                    combat: 10,
                    crewType: 'terracotta-merchant',
                },
                {
                    morale: 1310,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'terracotta-merchant',
                },
                {
                    morale: 1300,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'terracotta-merchant',
                },
                {
                    morale: 1300,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'terracotta-merchant',
                },
                {
                    morale: 900,
                    seafaring: 2900,
                    combat: 900,
                    crewType: 'kharidian-exile',
                    solidarity: true,
                },
                {
                    morale: 855,
                    seafaring: 2755,
                    combat: 855,
                    crewType: 'kharidian-exile',
                    solidarity: true,
                },
                {
                    morale: 720,
                    seafaring: 2320,
                    combat: 720,
                    crewType: 'kharidian-exile',
                    solidarity: true,
                },
            ],
            shipwright: {
                morale: 0.05,
                combat: 0.03,
                seafaring: 0.03,
            },
            captains: [
                {
                    morale: 1940,
                    seafaring: 1150,
                    combat: 0,
                    name: 'Alexander Drake',
                    crewType: 'captain',
                },
                {
                    morale: 1010,
                    seafaring: 1990,
                    combat: 1200,
                    spercent: 0.01,
                    name: 'Kang the Ghost',
                    crewType: 'captain',
                },
                {
                    morale: 1160,
                    seafaring: 1105,
                    combat: 1995,
                    cpercent: 0.01,
                    name: 'Barnabas Bonny',
                    crewType: 'captain',
                },
            ],
            shipParts: [
                {
                    type: 'hull',
                    name: 'Golden Katana Hull',
                    morale: 500,
                    combat: 500,
                    seafaring: 1200,
                },
                {
                    type: 'hull',
                    name: 'Blazing Lantern Hull',
                    morale: 1400,
                    combat: 500,
                    seafaring: 500,
                },
                {
                    type: 'hull',
                    name: 'Blackwater Hull',
                    morale: 850,
                    combat: 750,
                    seafaring: 1700,
                },
                {
                    type: 'hull',
                    name: 'Shimmering Azure Hull',
                    morale: 1325,
                    combat: 1325,
                    seafaring: 1325,
                },
                {
                    type: 'deck',
                    name: 'Overwhelmingly Large Cannon x4',
                    morale: 0,
                    seafaring: 0,
                    combat: 1750,
                },
                {
                    type: 'deck',
                    name: 'Bladewing Rigging',
                    morale: 0,
                    seafaring: 2000,
                    combat: 0,
                },
                {
                    type: 'deck',
                    name: 'Fineglow Lanterns',
                    morale: 2000,
                    seafaring: 0,
                    combat: 0,
                },
                {
                    type: 'ramFigurehead',
                    name: 'Figurehead of the Spires',
                    morale: 950,
                    seafaring: 100,
                    combat: 0,
                },
                {
                    type: 'ramFigurehead',
                    name: 'Ram of the Bladewing',
                    morale: 0,
                    seafaring: 0,
                    combat: 1100,
                },
            ],
        }
        const options = {
            target: {
                morale: 12800,
                seafaring: 12800,
                combat: 12800,
            },
            forceMerchant: true,
        }

        const results = calculate(portData, target)
        expect(results).toEqual({
            party: [
                {
                    index: 1,
                    use: true,
                    morale: 1010,
                    seafaring: 1990,
                    combat: 1200,
                    spercent: 0.01,
                    name: 'Kang the Ghost',
                    crewType: 'captain',
                },
                {
                    index: 3,
                    use: true,
                    type: 'hull',
                    name: 'Shimmering Azure Hull',
                    morale: 1325,
                    combat: 1325,
                    seafaring: 1325,
                },
                {
                    index: 4,
                    use: true,
                    type: 'deck',
                    name: 'Overwhelmingly Large Cannon x4',
                    morale: 0,
                    seafaring: 0,
                    combat: 1750,
                },
                {
                    index: 6,
                    use: true,
                    type: 'deck',
                    name: 'Fineglow Lanterns',
                    morale: 2000,
                    seafaring: 0,
                    combat: 0,
                },
                {
                    index: 8,
                    use: true,
                    type: 'ramFigurehead',
                    name: 'Ram of the Bladewing',
                    morale: 0,
                    seafaring: 0,
                    combat: 1100,
                },
                {
                    index: 0,
                    use: true,
                    morale: 4010,
                    seafaring: 0,
                    combat: 0,
                    crewType: 'zhonghu-player',
                },
                {
                    index: 6,
                    use: true,
                    morale: 40,
                    seafaring: 4210,
                    combat: 30,
                    crewType: 'stargazer',
                },
                {
                    index: 13,
                    use: true,
                    morale: 0,
                    seafaring: 0,
                    combat: 4200,
                    crewType: 'gu-bodyguard',
                },
                {
                    index: 18,
                    use: true,
                    morale: 1300,
                    seafaring: 0,
                    combat: 10,
                    crewType: 'terracotta-merchant',
                },
                {
                    index: 22,
                    use: true,
                    morale: 900,
                    seafaring: 2900,
                    combat: 900,
                    crewType: 'kharidian-exile',
                    solidarity: true,
                },
            ],
            total: { morale: 11901, seafaring: 11622, combat: 11602 },
            successChance: '90%',
        })
    })
})
